### ISSUE TITLE
conda command

### ISSUE THREAD

**Issue by kegl** [yandex-research/tabm#1]
Hi,

I think the conda command should be:

conda env create -f environment.yaml -n tabm

**Comment by kegl** [comment]
Also, out-of-box pip install would help me a lot, any chance to register it on pypi?

**Comment by Yura52** [comment]
Hi!

> I think the conda command should be:

Thank you for reporting this! I did not know about this property of conda. It turns out that:

- `conda create` [ignores](https://github.com/conda/conda/issues/13676) the name provided in the YAML file.
- There is no such issue for `micromamba create`, `mamba create` and (surprisingly) `conda env create`.

**Comment by Yura52** [comment]
> Also, out-of-box pip install would help me a lot, any chance to register it on pypi?

This is a good idea! I created a separate issue to make it more visible, and summarized the current recommendations: https://github.com/yandex-research/tabm/issues/3
